# Camunda 8 Configuration
camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      base-url: http://localhost:26500
      gateway-address: localhost:26500
      security:
        plaintext: true
    operate:
      base-url: http://localhost:8081
    tasklist:
      base-url: http://localhost:8082

# Spring Configuration
spring:
  application:
    name: urlaub-process
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.camunda.urlaub: DEBUG
    io.camunda: INFO
