# Camunda 8 Configuration
camunda:
  client:
    mode: saas
    auth:
      client-id: TeipwtMaBZoMNqNG39~K0VM6MEfV9zSf
      client-secret: J_8c44LIM3A~m.ZW-1zWlypK0WCqDLJ4w_gBkpN~rC5yXpph2Aow_gF6jj3vz7WP
    cloud:
      region: fra-1
      cluster-id: 91025e8e-d8e5-41d9-ac77-1f2f7a4cbac4
# Spring Configuration
spring:
  application:
    name: urlaub-process
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.camunda.urlaub: DEBUG
    io.camunda: INFO
